### ISSUE TITLE
Play/Pause Icons should be changed

### ISSUE THREAD

**Issue by zumbrunnen** [iambald/MiniPlay#6]
*  When music is playing:
  * Google Play Music shows a Pause icon
  * MiniPlay shows a Play icon
* When music is paused:
  * Google Play Music shows a Play icon
  * MiniPlay shows a Pause icon

A button shows you what you can achieve by clicking it - not what's going on right now. Or in other words: Music is playing, and you want to pause it. So you're looking for a Pause button. So I find the implementation of Google Play Music (and all other players I can remember) much better.

Please exchange the icons on the Play/Pause button.

Besides that: MiniPlay rocks!

**Comment by iambald** [comment]
Fixed in dcedfa634e596080572414663663141a22fae30c - I'll upload the updated version to the Chrome store tonight.

**Comment by zumbrunnen** [comment]
Thank you for the quick fix! :shipit:
