### ISSUE TITLE
Last.fm Scrobbling Broken

### ISSUE THREAD

**Issue by codysherman** [iambald/MiniPlay#9]
I can not scrobble and haven't been able to since Last.fm switched to the beta. I tried re-authentication, but it still doesn't work. Does the extension just need to be updated to the newer URL or API or something? Or is mine messed up?

**Comment by codysherman** [comment]
Any idea on when a fix will be looked into?

**Comment by iambald** [comment]
I'm looking into it, but a fix might be delayed - Last.fm's developer website has been buggy for me recently.

**Comment by iambald** [comment]
Fixed in 0.6.2, just published.

**Comment by codysherman** [comment]
Hmmmm, I kept getting Authentication error pop-up after updating. Uninstalled and reinstalled and am now just getting 'scrobbling failed'.

**Comment by iambald** [comment]
Whoops - should be fixed in 0.6.3, publishing now.

**Comment by codysherman** [comment]
I'm getting constant Scrobble failed errors again.

**Comment by iambald** [comment]
It's working on my end - try disabling and re-enabling scrobbling in the settings
